next/kubernetes/base/ingress.yml

www.bratislava.sk was not working

fixed missssssing www.

---

next/.dockerignore
next/.env.bratiska-cli-build.dev
next/.env.bratiska-cli-build.prod
next/.env.bratiska-cli-build.staging

- added bratiska build env vars
- updated dockerignore file to make docker independed from unwanted env vars

Updated env structure

---

next/kubernetes/base/kustomization.yml
next/kubernetes/base/ukrajina.ingress.yml

* Added ukrajina.ingress permanent redirect from ukrajina.[dev.|stage.]bratislava.sk to our /bratislava-pre-ukrajine webpage on the main bratislava site, based on cluster

feat: added permanent redirect from/to ukraine web

---

next/components/atoms/HomepageMarkdown.tsx
next/components/molecules/Sections.tsx
next/components/ui/AccordionItem/AccordionItem.tsx
next/components/ui/NarrowText/NarrowText.tsx
next/components/ui/NumericalListItem/NumericalListItem.tsx
next/pages/index.css

https://inovaciebratislava.atlassian.net/browse/BA-555
This PR fixes design issues with accordion items.

BA-555 Correct design issues in accordion item

---

next/components/forms/SelectField.tsx
next/components/styleguide/showcases/SelectFieldShowCase.tsx
next/pages/styleguide.tsx

add forward ref possibility to SelectField

feat: add forwardRef to SelectField

---

next/components/ui/Videos/Videos.tsx
next/components/ui/Videos/VideosService.ts

[JIRA ticket](https://inovaciebratislava.atlassian.net/browse/BA-724)

BA-724: Show button content based on video length

---

next/components/forms/SearchField.tsx

Fix SearchField placeholder when focus and icon opacity when disabled

FORM-172/Fix SearchField after review 

---

next/components/sections/WelcomeSection.tsx
next/components/ui/Bookmark/Bookmark.tsx
next/components/ui/Sections/Posts/Posts.tsx
next/pages/index.tsx
next/utils/page.ts

[JIRA](https://inovaciebratislava.atlassian.net/browse/BA-731)

BA-731: Encapsulate header components

---

next/components/forms/SearchField.tsx
next/components/styleguide/showcases/SearchFieldShowCase.tsx

Fixed issue with caret margins

Fixed Search Field component

---

next/components/forms/TextAreaField.tsx
next/components/styleguide/showcases/TextAreaFieldShowCase.tsx

fixed responsiveness issue with custom width of component

Form-173/TextArea Fix responsive view for mobile screens

---

next/backend/forms/test/schema.json
next/components/forms/widgets/TextAreaFieldWidgetRJSF.tsx

Just want to show multiple ways of select usage in rjsf schema.

FORM-226/rjsf-changes

---

next/components/molecules/sections/documentList/DocumentList.tsx
next/components/ui/AdvancedSearch/AdvancedSearch.tsx
next/components/ui/PageCard/PageCard.tsx
next/pages/vyhladavanie.tsx

- tmp fix colors in page results
- remove `minKeywordLength` because it's confusing with debaounced search
- removed header from search page to reduce "void space", new h1 is the search field heading
- some cleanup in changed components

fix colors on search page results, more minor fixes

---

next/.eslintrc.js
next/components/ui/SubpageList/SubpageList.tsx

[JIRA ticket](https://inovaciebratislava.atlassian.net/browse/BA-572)

BA-572: Fix overlapping subpage headlines

---

strapi/package.json
strapi/yarn.lock

Step by step upgrade due to https://github.com/strapi/strapi/issues/14978#issuecomment-1346312535

Upgrade strapi to v4.4

---

next/backend/meili/fetchers/homepageFetcher.ts
next/components/ui/Videos/Videos.tsx

- add `/blog` into link in homepage search suggestions for Blog posts
- show all videos - just quick fix, needs change in query and cleanup

BA-753, BA-724: small quick fixes in blog posts search link and video section

---

next/components/forms/simple-components/Toggle.tsx
next/components/styleguide/showcases/ToggleShowCase.tsx

made controlled state logic, fix css styles

Form-178/Fix toggle button

---

next/components/forms/icon-components/ExpandMoreIcon.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxDetails.tsx
next/components/forms/segments/AccountSections/TaxesFeesSection/TaxFeeSection.tsx
next/components/forms/simple-components/Accordion.tsx
next/components/styleguide/showcases/AccordionShowCase.tsx
next/public/locales/en/account.json
next/public/locales/sk/account.json

Fixed Accordion component style (added 4th size and made mobile design). Created Tax Details visual page

Form-264/TaxDetails_Visual

---

next/pages/bratislava.css

Move safari key icon to the left for fields with type password

Form-333/SafariPasswordField

---

next/components/styleguide/showcases/ServiceCardShowCase.tsx

Form-230/FixStyleguideIcons

---

next/components/forms/widget-components/InputField/InputField.tsx

Reverts bratislava/bratislava.sk#691

Revert "Form-338/CapitalLetter"

---

next/graphql/index.ts
next/graphql/queries/Homepage.graphql
strapi/schema.graphql
strapi/src/api/homepage/content-types/homepage/schema.json
strapi/src/components/blocks/top-services-item.json
strapi/src/components/sections/top-services.json

#765: add top services section to homepage strapi model

---

next/components/ui/Carousel/Carousel.tsx
next/components/ui/Sections/BlogCards/BlogCards.tsx
next/components/ui/VerticalCardButton/VerticalCardButton.tsx

Properly show and hide carousel control buttons.

fix hiding of control buttons on hp blog carousel

---

next/components/molecules/sections/general/AccordionSection.tsx
next/components/ui/AccordionV2/AccordionV2.tsx
next/components/ui/Institution/Institution.tsx

#828 institution layout

---

next/backend/graphql/index.ts
next/backend/graphql/queries/General.graphql
next/components/organisms/NavBar/AlertBanner.tsx
next/components/ui/AccordionItem/AccordionItem.tsx

Before the Alert was rendered on first load of page, even if it was deleted from strapi.
Todo: 
- remove Alert from generalContext if this solution works fine

#657: load alert from client

---

next/components/molecules/sections/general/DocumentListSection/DocumentListModalBody.tsx
next/components/molecules/sections/homepage/WelcomeHomepageSection.tsx
next/components/pages/generalPageContent.tsx
next/components/pages/searchPageContent.tsx
next/components/ui/FileList/FileList.tsx
next/components/ui/Footer/DesktopFooter.tsx
next/package.json
next/utils/formatFileSize.ts
next/yarn.lock

#785: filecard format filesize

---

next/components/molecules/sections/general/DocumentListSection/RegulationModalBody.tsx
next/components/molecules/sections/general/DocumentListSection/RegulationsResults.tsx
next/components/ui/ModalDialog/ModalDialog.tsx

TODO: needs revisit - close on Esc or on click outside does not work

#991: tmp fix modal overflow

---

next/components/molecules/sections/homepage/HighlightsHomepageSection.tsx

Unified height of cards at HP novinky

1014/Unify height of cards at HP Novinky

---

next/components/ui/Videos/Videos.tsx

**Na malych displejoch robilo toto:**
**Teraz takto**

Video carousel - uprava medzier medzi videami na mensich displejoch

---

next/backend/graphql/index.ts
strapi/schema.graphql
strapi/src/api/inba-article/content-types/inba-article/schema.json

- remove dynamic sections
- add richtext field as `content`
- add `perex`
- more field to be added based on requirements
ref #1036

#1036: simplify in.ba article content to single richtext instead of sections

---

next/backend/meili/fetchers/blogPostsFetcherReactQuery.ts
next/backend/meili/fetchers/inbaArticlesFetcher.ts
next/backend/meili/types.ts
next/components/molecules/Sections.tsx
next/components/molecules/sections/general/ArticlesListSection/BlogPostsByTags.tsx
next/components/molecules/sections/general/ArticlesListSection/InbaArticlesByTags.tsx
next/components/ui/Footer/FooterShared.tsx
strapi/config/plugins.meilisearch.config.ts

- implement section to display all inba articles paginated
- using meilisearch - for filtering (in future)
TODO
- show tags
- inba article detail page - probably living on `/inba/blog/[slug]`

#1038 inba section

---

next/backend/graphql/index.ts
next/backend/graphql/queries/InbaArticles.graphql
next/components/pages/InbaArticlePageContent.tsx
next/pages/inba/blog/[slug].tsx

- implement page by slug libing on `/inba/blog/[slug]`
TODO
- show tags

#1038: implement detail page for inba articles by slug

---

next/backend/graphql/index.ts
next/backend/graphql/queries/InbaArticles.graphql
next/backend/meili/fetchers/inbaArticlesFetcher.ts
next/backend/meili/types.ts
next/components/molecules/sections/general/ArticlesListSection/InbaArticlesByTags.tsx
next/components/pages/InbaArticlePageContent.tsx
strapi/config/plugins.meilisearch.config.ts
strapi/schema.graphql
strapi/src/api/inba-article/content-types/inba-article/schema.json
strapi/src/api/inba-tag/content-types/inba-tag/schema.json

- remove `tags` multirelation field from inba articles
- add `inbaTag` single relation field 
- show tag on FE in page header and also in cards

#1038: refactor inba tags to single inbaTag and display it on FE

---

next/backend/meili/fetchers/inbaArticlesFetcher.ts
next/components/molecules/sections/general/ArticlesListSection/InbaArticlesByTags.tsx
next/components/pages/InbaArticlePageContent.tsx
next/pages/inba/text/[slug].tsx

- fixes #1063 
- fixes #1062 
- change  url from `/inba/blog/[slug]` to `/inba/text/[slug]`

#1063, #1063: display perex, change /blog/ to /text/ + minor fixes

---

next/backend/graphql/index.ts
strapi/schema.graphql
strapi/src/api/general/content-types/general/schema.json
strapi/src/api/inba-article/content-types/inba-article/schema.json
strapi/src/api/inba-release/content-types/inba-release/schema.json
strapi/src/api/inba-release/controllers/inba-release.ts
strapi/src/api/inba-release/routes/inba-release.ts
strapi/src/api/inba-release/services/inba-release.ts

#1065: create new content type InbaReleases

---

next/backend/graphql/index.ts
next/backend/graphql/queries/General.graphql
next/backend/graphql/queries/InbaReleases.graphql
next/backend/graphql/queries/Sections.graphql
next/backend/graphql/queries/Vzn.graphql
next/components/molecules/ShareButtons.tsx
next/components/pages/InbaArticlePageContent.tsx
next/components/pages/InbaReleasePageContent.tsx
next/components/pages/blogPostPageContent.tsx
next/messages/sk.json
next/pages/inba/archiv/[slug].tsx

#1065: implement detail page for Inba Releases

---

next/backend/graphql/index.ts
next/components/atoms/StrapiImage.tsx
next/components/pages/InbaArticlePageContent.tsx
next/components/pages/InbaReleasePageContent.tsx
next/components/ui/Links/Links.tsx
next/messages/en.json
next/messages/sk.json
strapi/schema.graphql
strapi/src/api/page/content-types/page/schema.json
strapi/src/components/sections/inba-releases.json

- resolves #1065 
- add translations
- improve layout on detail page
- add strapi section "inba releases"

#1065: add section inba releases, improve detail page layout

---

next/backend/graphql/fetchers/inbaReleases.fetcher.ts
next/backend/graphql/index.ts
next/backend/graphql/queries/InbaReleases.graphql
next/backend/graphql/queries/Sections.graphql
next/components/molecules/Sections.tsx
next/components/molecules/presentation/InbaReleaseHorizontalCard.tsx
next/components/molecules/sections/general/InbaReleasesSection.tsx
next/components/pages/InbaReleasePageContent.tsx
next/tailwind.config.js

- resolves #1065 
- implement FE part for inba releases section

#1065: implement inba releases section FE part

---

next/backend/graphql/index.ts
next/backend/graphql/queries/InbaArticles.graphql
next/components/pages/InbaArticlePageContent.tsx
next/messages/en.json
next/messages/sk.json

No styleguide, so the position is decided just by rule of thumb.
Also added english translation but current date-formatting function doesn't react to language change

Add information about magazine issue for inba articles

---

next/components/forms/simple-components/Button.tsx
next/components/forms/simple-components/Tag.tsx
next/components/forms/widget-components/Modals/MessageModal.tsx
next/components/forms/widget-components/Modals/Modal.tsx
next/components/molecules/HomePageSearchField.tsx
next/components/molecules/SkipToContentButton.tsx
next/components/molecules/sections/general/CalculatorSection/MinimumCalculator.tsx
next/components/organisms/Carousel/CarouselControlButton.tsx
next/components/organisms/CookieConsent.tsx
next/components/organisms/Gallery/GalleryModal.tsx
next/components/organisms/Gallery/ImageLightBox.tsx
next/components/organisms/NavBar/NavBarHeader/NavBarHeader.tsx
next/components/organisms/NavBar/NavMenu/MobileNavMenu.tsx
next/components/styleguide/showcases/ButtonShowCase.tsx
next/components/ui/Banner/Banner.tsx
next/components/ui/Contact/Contact.tsx
next/components/ui/ModalDialog/Dialog.tsx
next/components/ui/PageHeader/PageHeader.tsx
next/components/ui/Pagination/Pagination.tsx
next/components/ui/VerticalCardButton/VerticalCardButton.tsx
next/messages/en.json
next/messages/sk.json
next/package.json
next/yarn.lock

- use ButtonNew from konto as Button on bratislava.sk
- update props in usage
- upgrade tailwindcss
- use RAC Button instead of `useButton` hook
- it should work also in e.g. [DialogTrigger](https://react-spectrum.adobe.com/react-aria/Dialog.html#dialog) or [MenuTrigger](https://react-spectrum.adobe.com/react-aria/Menu.html#menu), that didn't work before
- https://github.com/bratislava/component-library/issues/4
TODO
- test if all variant works as they should, mainly links should be tested properly
- doublecheck if everyhing is okay with refs, MLink used as it is now without useButton hook...

Use Button from konto

---

next/backend/ms-graph/server/searchInOrgStructure.ts
next/components/pages/searchPageContent.tsx
next/components/ui/AdvancedSearch/AdvancedSearch.tsx
next/package.json
next/pages/api/ms-graph/search-in-structure.ts
next/yarn.lock

- fixes search in #1139
- enable search in AD by default (as prep for search refactor)

fix AD search with diacritics

---

next/components/ui/Divider/Divider.tsx

Fix divider

---

next/components/molecules/Regulations/RegulationCard.tsx
next/components/molecules/SearchPageNew/useQueryBySearchOption.ts
next/components/molecules/sections/general/ArticlesListSection/InbaArticlesList.tsx
next/components/pages/InbaArticlePageContent.tsx
next/components/styleguide/showcases/AccordionShowcase.tsx
next/components/ui/InbaFeaturedArticles/InbaFeaturedArticles.tsx
next/pages/blog/[slug].tsx
next/pages/inba/archiv/[slug].tsx
next/pages/inba/clanky/[slug].tsx
next/pages/vzn/[slug].tsx

- change url from `/inba/text/[slug]` to `/inba/clanky/[slug]` - resolves #1172 
- do not show "Publikovane v ..." if no `inbaRelease` is provided
- resolves #1174 
+ change some accordion titles is showcase

Change inba articles url

---

next/components/molecules/sections/general/AccordionSection.tsx
next/components/styleguide/showcases/AccordionShowcase.tsx
next/components/ui/AccordionV2/AccordionV2.tsx

After discussion with designer, this setup with multiple sizes was wrong. We even used only one size. This PR unifies all variants to only one used variant.

unify accordion sizes to only one

---

next/components/molecules/sections/homepage/HomepageTabs/TabPanelOfficialBoard.tsx
next/components/organisms/SearchSection/SearchResultCard.tsx
next/components/organisms/SearchSection/useQueryBySearchOption.ts

- change order official board card metadata to match other cards
- add white background

minor visual fixes in search result cards

---

next/backend/ginis/fetchers/officialBoardListFetcher.ts
next/backend/ginis/server/getOfficialBoardParsedList.ts
next/backend/ginis/types.ts
next/components/molecules/sections/general/OfficialBoardSection/OfficialBoardAdditionalFilters.tsx
next/components/organisms/SearchSection/GlobalSearchSectionContent.tsx
next/ginis-sdk/api/json/ude/seznam-dokumentu.ts
next/messages/en.json
next/messages/sk.json
next/pages/api/ginis/official-board-list.ts

- add filter to publication state, discussed with OSO, approved for testing on staging

#1215 add filter by publication state to official board

---

next/backend/graphql/index.ts
strapi/schema.graphql
strapi/src/api/page/content-types/page/schema.json
strapi/src/components/blocks/testimonial-item.json
strapi/src/components/sections/testimonials.json

add Testimonials section to strapi

---

next/components/forms/simple-components/Button.tsx
next/components/ui/Brand/Brand.tsx
next/components/ui/Breadcrumbs/DesktopBreadcrumbs.tsx
next/components/ui/Links/Links.tsx

#1242: fix shrinking link icons

---

next/next.config.js

#1259 Add redirects for new slugs of contact pages

---

next/pages/404.tsx
tests/cypress/e2e/404Page.cy.ts

Add new test for 404 page

---

next/kubernetes/envs/Prod/behdevin.ingress.yml
next/kubernetes/envs/Prod/kustomization.yml

* Add prod only kubernetes Ingress aliases for behdevin.bratislava.sk and devin-bratislava.sk

Added k8 Ingress alias for behdevin.bratislava.sk

---

.github/workflows/cypress-test.yml
tests/cypress/e2e/englishTranslation.cy.ts

Fix: english translation

---

next/components/cards/FileCard.tsx
next/components/cards/FileRowCard.tsx
next/components/page-contents/RegulationPageContent.tsx

- Update paddings, margins and element dimensions to match the new DS
- Add new card variant with horizontal divider
- Handle responsiveness
- Design reference for group display: [Mestsky web (bratislava.sk)](https://www.figma.com/design/A9aoQH2FGhR1D14wvvk6FW/Mestsky-web-(bratislava.sk)?m=dev&node-id=2052-2119)

#1298 Update FileRowCard component to match the new DS

---

next/components/sections/SearchSection/SearchResultCard.tsx
next/components/sections/SearchSection/SearchResults.tsx
next/components/sections/homepage-sections/HomepageTabs/TabPanelOfficialBoard.tsx

- Change the card's design according to DS
- Change the group's design according to DS (add a border)

#1300 Update SearchResultCard and group according to DS

---

next/kubernetes/base/deployment.yml
next/kubernetes/envs/Dev/config.json
next/kubernetes/envs/Prod/config.json
next/kubernetes/envs/Prod/kustomization.yml
next/kubernetes/envs/Prod/pdb.yml
next/kubernetes/envs/Staging/config.json

* Change `readinessProbe` to run more often with deployment becoming unready after 30sec
* Added `livenessProbe` to restart the deployment after 90sec
* Added PDB to increase availability in production environment
* Change resource requests & limits based on long term monitoring

Added livenessProbe & PDB. Change resource limits

---

next/components/common/FileList/FileList.tsx
next/components/sections/FileListSection.tsx

This is part of the File List refactoring in #1334

#1342 Show section title instead of category in File List when used

---

next/components/common/FileList/FileList.tsx
next/components/sections/AccordionSection.tsx
next/components/sections/FileListSection.tsx

This is part of the File List refactoring in https://github.com/bratislava/bratislava.sk/issues/1334

#1344 Display File List always as rows variant

---

next/components/common/FaqsGroup/FaqsGroup.tsx
next/components/layouts/Sections.tsx
next/components/sections/FaqCategoriesSection.tsx
next/components/sections/FaqsSection.tsx
next/services/graphql/index.ts
next/services/graphql/queries/Faqs.graphql
next/services/graphql/queries/Sections.graphql
strapi/schema.graphql
strapi/src/api/faq-category/content-types/faq-category/schema.json
strapi/src/api/faq-category/controllers/faq-category.ts
strapi/src/api/faq-category/routes/faq-category.ts
strapi/src/api/faq-category/services/faq-category.ts
strapi/src/api/faq/content-types/faq/schema.json
strapi/src/api/faq/controllers/faq.ts
strapi/src/api/faq/routes/faq.ts
strapi/src/api/faq/services/faq.ts
strapi/src/api/page/content-types/page/schema.json
strapi/src/components/sections/faq-categories.json
strapi/src/components/sections/faqs.json

#1323 Add Faqs as content type

---

next/kubernetes/base/kariera.ingress.yml
next/kubernetes/base/kustomization.yml

* New redirect for `kariera.bratislava.sk` pointing to https://bratislava.sk/mesto-bratislava/sprava-mesta/magistrat/pracovne-prilezitosti
* Closes #1351

Added new redirect to for kariera.bratislava.sk

---

next/components/common/NavBar/NavMenu/MobileNavMenuContent.tsx

https://github.com/user-attachments/assets/4025174b-56b6-4bf1-bd63-23ed8724501e

Fix unintended press propagation on mobile menu back button

---

next/public/locales/en/translation.json
next/public/locales/sk/translation.json

#1365 Update translations in blogposts filter

---

.github/workflows/deploy.yml

adding debug flag for prod deploy that we will have more output on bratiska-cli

added debug flag for prod deploy

---

.gitignore
docker-compose.yml

1. `docker-compose up`
2. Load a dump into you local strapi - new folder `postgres` should be created (and gitignored, the same way aj `meilisearch` folder)
3. Start Strapi and check if you have data.
4. Kill strapi and docker container.
5. Go to other repo and do the same
6. Return to this repo, run `docker-compose up`, start Strapi and you should still have all data ✅

#1378 Correctly setup postgres persistent volume for local development

---

strapi/database/migrations/2023.06.14T00.00.00.update-file-paths.js
strapi/package.json
strapi/patches/@strapi+admin+4.11.4.patch
strapi/yarn.lock

- continuously upgrade Strapi, now to v4.11.4
- add migration script accordign to migration guides https://docs-v4.strapi.io/dev-docs/migration/v4/migration-guide-4.7.0-to-4.11.4
- update patch for admin panel

#1422 Upgrade Strapi to v4.11.4

---

strapi/package.json
strapi/patches/@strapi+admin+4.14.0.patch
strapi/schema.graphql
strapi/types/generated/components.d.ts
strapi/types/generated/contentTypes.d.ts
strapi/yarn.lock

- continuously upgrade strapi (to v.4.14.0)
- generate types according to migration guide https://docs-v4.strapi.io/dev-docs/migration/v4/migration-guide-4.11.4-to-4.14.0
- update patches

#1412 Upgrade Strapi to v4.14.0

---

.github/workflows/codeql-analysis.yml
.github/workflows/cypress-test.yml

We get this error so trying to use newer version:

Use actions/upload-artifact@v4

---

.github/workflows/comment-after-release.yml

Add release comments workflow

---

next/src/components/formatting/Markdown/Markdown.tsx

#1468 Enable phone number in Richtext

---

next/public/locales/en/translation.json
next/public/locales/sk/translation.json
next/src/components/common/NavBar/NavBar.tsx
next/src/components/common/NavBar/NavMenu/NavMenu.tsx
next/src/components/common/ScrollToTopButton/ScrollToTopButton.tsx
next/src/components/layouts/PageLayout.tsx

- ### Add line instead of shadow
- ### Remove stickness
- ### Remove hidden empty block
- ### Add scroll to top button

#1398 make the menu non sticky

---

strapi/.env.example
strapi/config/plugins.ts
strapi/config/server.ts
strapi/kubernetes/base/.env
strapi/kubernetes/envs/Dev/.env
strapi/kubernetes/envs/Prod/.env
strapi/package-lock.json
strapi/package.json

Setup mailgun email provider for Strapi
Allow sending forgoten email to admin user.

#1452 Setup mailgun email provider

---

strapi/kubernetes/envs/Staging/.env

Add missing staging env variable for lost password email setup.

1452-missing-env-variable

---

next/src/components/cards/EventCard.tsx
next/src/components/cards/FileRowCard.tsx
next/src/components/common/Accordion/Accordion.tsx
next/src/components/common/Brand/Brand.tsx
next/src/components/common/Breadcrumbs/DesktopBreadcrumbs.tsx
next/src/components/common/Breadcrumbs/MobileBreadcrumbs.tsx
next/src/components/common/Chip/Chip.tsx
next/src/components/common/Contacts/Contacts.tsx
next/src/components/common/FaqsGroup/FaqsGroup.tsx
next/src/components/common/Gallery/Gallery.tsx
next/src/components/common/NumericalList_Deprecated/NumericalListItem_Deprecated.tsx
next/src/components/common/OrganizationalStructure_Deprecated/OrganizationalStructureAccordionCard_Deprecated.tsx
next/src/components/common/Tag/Tag.tsx
next/src/components/formatting/Markdown/Markdown.tsx
next/src/components/page-contents/ArticlePageContent.tsx
next/src/components/sections/CalculatorSection_Deprecated/MinimumCalculator_Deprecated.tsx
next/src/components/sections/TestimonialsSection.tsx
next/src/components/sections/homepage-sections/HomepageTabs/HomepageTabs.tsx
next/src/components/styleguide/Stack.tsx
next/src/components/styleguide/showcases/MarkdownShowcase.tsx
next/src/pages/styleguide.tsx
next/src/styles/globals.css
next/tailwind.config.js

Discussed with Patrik.
Implemented according to Foundations https://www.figma.com/design/ctDKMhAPIjLUVNNmq430D4/DS--Foundations?node-id=59-21&p=f&m=dev
Main change is that the default text changes from 20px to 18px.

#1384 Cleanup text sizes

---

next/src/services/graphql/index.ts
next/src/services/graphql/queries/Sections.graphql
strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.regulations-list.json
strapi/schema.graphql
strapi/src/components/sections/regulations-list.json
strapi/types/generated/components.d.ts

/mesto-bratislava/sprava-mesta/legislativa-mesta/vseobecne-zavazne-nariadenia

#1504 Remove unused fields from Regulations list section

---

next/src/components/common/OrganizationalStructure_Deprecated/OrganizationalStructureAccordionCard_Deprecated.tsx
next/src/components/common/OrganizationalStructure_Deprecated/OrganizationalStructureAccordionCards_Deprecated.tsx
next/src/components/common/OrganizationalStructure_Deprecated/OrganizationalStructureAccordion_Deprecated.tsx
next/src/components/common/OrganizationalStructure_Deprecated/OrganizationalStructureTopLevelAccordion_Deprecated.tsx
tests/cypress/e2e/organizationalStructure.cy.ts

I just spent 15 minutes to get rid of the ugliest parts...
Before, on some screensizes it was broken:

#1507 Minor improvements in organizational structure FE

---

next/src/components/common/Gallery/Gallery.tsx
next/src/utils/useTailwindBreakpointValue.ts

Gallery was redesigned according to [new Figma design](https://www.figma.com/design/17wbd0MDQcMW9NbXl6UPs8/DS--Component-library?node-id=16846-35038&m=dev)

#1396 Implement new design for Gallery

---

next/src/components/common/Breadcrumbs/DesktopBreadcrumbs.tsx
next/src/components/common/Breadcrumbs/MobileBreadcrumbs.tsx

Fix accidentally changed homepage ling during refactoring.
Fix typo.

#1521 Fix breadcrumbs homepage link

---

next/src/components/common/NavBar/NavMenu/NavMenuLink.tsx
next/src/components/common/NavBar/NavMenu/NavMenuSection.tsx
next/src/components/common/NavBar/NavMenu/getParsedMenus.ts
next/src/components/common/NavBar/NavMenu/navMenuTypes.ts
next/src/components/common/SubpageList_Deprecated/SubpageList_Deprecated.tsx
next/src/utils/getLinkProps.ts

- add hover style in SubpageList header section
- use getLinkProps in menu
- show external link icon in menu links

#1284 Use CommonLinkProps type and getLinkProps also in Menu

---

next/src/pages/[...slug].tsx
next/src/pages/inba/archiv/[slug].tsx
next/src/pages/inba/clanky/[slug].tsx
next/src/pages/index.tsx
next/src/pages/spravy/[slug].tsx
next/src/pages/styleguide.tsx
next/src/pages/uradna-tabula/[slug].tsx
next/src/pages/vyhladavanie.tsx
next/src/pages/vzn/[slug].tsx
next/src/utils/consts.ts

We got into "stucked 404" situation several times on other projects, and this was usually the solution.
Let's try if this helps also in the case of stuck 404 on EN homepage on bratislava.sk.

#1286 Use NOT_FOUND const with revalidate

---

next/src/components/sections/SearchSection/useQueryBySearchOption.ts
next/src/services/graphql/index.ts
next/src/utils/dev/strapiHelper.ts
strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##page.page.json
strapi/schema.graphql
strapi/src/api/page/content-types/page/schema.json
strapi/types/generated/contentTypes.d.ts

I checked staging and prod for empty titles and long titles and titles containing newlines and updated those pages (only 2 testing pages were missing the title), so this PR can be safely merged.

#1532 Make title required and short in Pages

---

next/src/components/common/Timeline/Timeline.tsx
next/src/components/sections/TextWithImageOverlappedSection.tsx
next/src/components/sections/TextWithImageSection.tsx
next/src/services/graphql/index.ts
next/src/services/graphql/queries/Sections.graphql
strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.text-with-image-overlapped.json
strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.text-with-image.json
strapi/schema.graphql
strapi/src/components/sections/text-with-image-overlapped.json
strapi/src/components/sections/text-with-image.json
strapi/types/generated/components.d.ts

#1548 Add CTA buttons to Text with image sections

---

next/src/components/layouts/Sections.tsx
next/src/components/sections/ColumnsSection.tsx
next/src/components/sections/PartnersSection.tsx
next/src/services/graphql/index.ts
next/src/services/graphql/queries/Sections.graphql
strapi/config/sync/core-store.plugin_content_manager_configuration_components##blocks.partner.json
strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.partners.json
strapi/schema.graphql
strapi/src/api/page/content-types/page/schema.json
strapi/src/components/blocks/partner.json
strapi/src/components/sections/partners.json
strapi/types/generated/components.d.ts
strapi/types/generated/contentTypes.d.ts

Examples of pages with some logos where I locally used Partners section:
https://bratislava.sk/doprava-a-mapy/doprava/dopravne-projekty/modernizacia-elektrickovych-trati-karloveska-radiala-projektova-dokumentacia
http://localhost:3000/zivotne-prostredie-a-vystavba/klima/klimaticka-vyzva

#1558 Add Partners section

---

next/src/components/common/Videos_Deprecated/Videos_Deprecated.tsx

Just quickfix. The whole section will be refactored.

#1585 Fix Videos heading level

---

next/src/components/cards/ContactCtaCard.tsx
next/src/components/common/Contacts/Contacts.tsx
strapi/config/sync/core-store.plugin_content_manager_configuration_components##blocks.contact-person-card.json

#1555 Add links to personContacts email and phone

---

strapi/patches/strapi-plugin-meilisearch+0.13.2.patch

For context, see related issue
A workaround is proposed in this PR - patch the plugin until the it is fixed by maintainers.

#1670 Patch strapi-plugin-meilisearch to temporarily fix meilisearch indexing

---

next/src/services/graphql/index.ts
next/src/services/graphql/queries/Articles.graphql
next/src/services/meili/fetchers/articlesFetcher.ts
next/src/services/meili/types.ts
strapi/config/plugins.meilisearch.config.ts
strapi/config/sync/admin-role.admin-clanky-lmg395y8.json
strapi/config/sync/admin-role.admin-lg0mm2j6.json
strapi/config/sync/admin-role.starz-md207wo9.json
strapi/config/sync/admin-role.strapi-super-admin.json
strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##article-category.article-category.json
strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##article.article.json
strapi/schema.graphql
strapi/src/api/article-category/content-types/article-category/schema.json
strapi/src/api/article-category/controllers/article-category.ts
strapi/src/api/article-category/routes/article-category.ts
strapi/src/api/article-category/services/article-category.ts
strapi/src/api/article/content-types/article/schema.json
strapi/types/generated/contentTypes.d.ts

- While working on this task, I encountered a bug in Meilisearch strapi plugin - new entries are not indexed as of Strapi v5 upgrade. More details are in a separate issue: https://github.com/bratislava/bratislava.sk/issues/1670 
- Config sync export for Starz admin role is included in this PR. It is not the final role setup, it will be finished in issue https://github.com/bratislava/bratislava.sk/issues/1656

#1661 starz articles add articlecategory

---

next/src/components/layouts/Sections.tsx
next/src/components/page-contents/GeneralPageContent.tsx
next/src/components/sections/ArticlesSection/ArticlesAll.tsx
next/src/components/sections/DocumentsSection/DocumentsSection.tsx
next/src/components/sections/TootootEventsSection.tsx
next/src/components/sections/homepage-sections/HighlightsHomepageSection.tsx

- Revisiting code review comments from #1642 
- Page layout was broken when no sidebar was added, so I snuggled this into this PR

#1649 techdebt section cleanup part 2

---

next/src/components/layouts/SectionContainer.tsx
next/src/components/page-contents/GeneralPageContent.tsx

- Fixed incorrect width of the left column in page layout with sidebar
- Renamed data-section-container-... attributes to satisfy react warning

#1689 Sidebar layout - cleanup

---

next/src/components/cards/InbaReleaseCard.tsx
next/src/components/common/Button/Button.tsx
next/src/components/common/PageHeader/PageHeader.tsx
next/src/components/page-contents/InbaReleasePageContent.tsx
next/src/styles/globals.css

#1569 Redesign inba release detail page header

---

next/src/components/sections/SearchSection/SearchResultCard.tsx

#1740 Always show image placeholder in SearchResultCard

---

next/src/components/common/TableOfContents/TableOfContents.tsx
next/src/components/layouts/Sections.tsx
next/src/components/page-contents/GeneralPageContent.tsx

#1750 Table of contents small fixes

---

strapi/config/sync/admin-role.strapi-super-admin.json
strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##page.page.json

Export some other configs-sync updated exports

---

next/src/components/page-contents/InbaReleasePageContent.tsx
next/src/components/page-contents/OfficialBoardDocumentPageContent.tsx
next/src/components/sections/SearchSection/GlobalSearchSectionContent.tsx
next/src/services/ginis/mocks.ts
next/src/services/meili/fetchers/articlesFetcher.ts
next/src/services/meili/fetchers/inbaArticlesFetcher.ts

Make filters by ids optional in articlesFetcher and inbaArticlesFetcher

---

next/src/components/sections/NewsletterSection/NewsletterSection.tsx

NesletterSection small fixes
