- README.md
- next/.env.development
- next/README.md
- strapi/README.md
Changes based on recent onboarding - should be better default. Will update the Strapi README again once newer version of docs site is published (may take another week).
> Change .env.development STRAPI_URL, docs update

- next/components/ui/VisibilityIntersection/VisibilityIntersectionWrapper.tsx
- next/components/ui/VisibilityIntersection/useIntersectionObserver.ts
This is a new component + hook w/ logic using `IntersectionObserver` API to make it easier when to show sticky navigation menu and when regular navigation.
It is unused currently, as this is a first of other PRs to refactor entire logic for showing navigation menu.
> BA-488: Create unused logic for intersection check

- strapi/kubernetes/base/stateful-set-meilisearch.yml
This PR adds more time for meilisearch to initialize and properly start. Therefore strapi isnot contacting meilisearch when not ready.
> Meilisearch bugfix

- next/components/ui/BANavBar/BANavBar.tsx
- next/components/ui/BlogSearchCard/BlogSearchCard.tsx
- next/components/ui/DocumentCard/DocumentCard.tsx
- next/components/ui/DocumentListItem/DocumentListItem.tsx
- next/components/ui/HorizontalCard/HorizontalCard.tsx
- next/components/ui/InBaCard/InBaCard.tsx
- next/components/ui/NewsCard/NewsCard.tsx
- next/components/ui/PrimatorCard/PrimatorCard.tsx
- next/components/ui/Rent/Rent.tsx
- next/components/ui/Sections/BlogCards/BlogCards.tsx
- next/components/ui/Sections/Posts/Posts.tsx
- next/components/ui/TopNineItem/TopNineItem.tsx
- next/package.json
- next/pages/index.css
- next/tailwind.config.js
- next/yarn.lock
Few accessibility and UX quick fixes:
- make all "cards" on homepage clickable properly
- use `after:absolute after:inset-0` on links in card, and `relative` on card top div, so the link `::after` covers the whole card, therefore the whole card is clickable as a link
- remove cursor-pointer where it is redundant or deceptive
- add `@tailwindcss/line-clamp` plugin and remove custom line-clamp non-reliable css classes
- few more minor visual and UX fixes
I tried to touch as few chunks of code as possible :), just repaired what I aimed for.
> Fix: Make cards on homepage clickable properly

- next/backend/meili/fetchers/blogPostsFetcher.ts
- next/components/atoms/HomepageMarkdown.tsx
- next/components/forms/info-components/Tooltip.tsx
- next/components/forms/widget-components/RadioButton/Radio.tsx
- next/components/ui/BlogSearchCard/BlogSearchCard.tsx
- next/components/ui/Contact/Contact.tsx
- next/components/ui/Institution/Institution.tsx
- next/components/ui/Rent/Rent.tsx
- change `break-all` class to `break-words` - this should be quick fix for unwanted word breaks in the middle of words
- tmp fix sorting of blogposts in search results by date_added
- formatting
> change break-all to break-words, sort Blogposts in search by date_added

- next/next.config.js
- next/sentry.client.config.js
- next/sentry.server.config.js
First like this, once we're set on switching to an alternative will remove completely.
> Turn off Sentry

- next/components/atoms/CardGradient.tsx
- next/components/layouts/PageLayout.tsx
- next/components/molecules/OrganizationalStructure/OrganizationalStructure.tsx
- next/components/organisms/CookieConsent.tsx
- next/components/organisms/NavBar/MobileNavBar.tsx
- next/components/organisms/NavBar/NavBar.tsx
- next/components/organisms/NavBar/NavBarHeader/NavBarHeader.tsx
- next/components/organisms/NavBar/NavMenu/MobileNavMenu.tsx
- next/components/organisms/NavBar/NavMenu/NavMenu.tsx
- next/components/organisms/NavBar/NavMenu/NavMenuContent.tsx
- next/components/ui/WeddingForm/WeddingForm.tsx
- set `z-index` for parent elements to set stacking context
- improve cookie consent banner
- #784 remove dividers in organization structure
- move Account button to higher position in mobile menu 
- remove `pointer-events-...` in menu
- click outside menu is solved by Viewport set to full screen an z-index under NavBarHeader (NavBarHeader and menu are still clickable while menu is open, but the rest of the body is not)
- fix minor bugs and eslint errors (part of #839)
> Fix menu overlays

- next/components/ui/Iframe/Iframe.tsx
Remove deprecated attribute `scrolling` and add `sandbox="allow-scripts"` that should prevent iframes to colect cookies.
> add sandbox to iframe

- next/graphql/index.ts
- next/graphql/queries/BlogPosts.graphql
- strapi/schema.graphql
- strapi/src/api/blog-post/content-types/blog-post/schema.json
- strapi/src/api/page-category/content-types/page-category/schema.json
- strapi/src/api/page-subcategory/content-types/page-subcategory/schema.json
- strapi/src/api/tag/content-types/tag/schema.json
Allow internationalisation for Tags content type. Closes #809 
Remove unused field in Page Category and Page Subcategory content types.
> #809: add internationalisation to Tags

- next/kubernetes/base/platbadane.ingress.yml
- next/kubernetes/base/ukrajina.ingress.yml
* change letsencrypt cluster issuer to dns01 websupport for all redirects. All redirects couldn't get normal certificate through http01 challenge. Changing it to dns01 seems to work.
> fix: change cert issuer to dns01 for all redirects

- next/kubernetes/base/ukrajina.ingress.yml
Change env variable HOSTNAME to BRATISKA_HOSTNAME for all redirects that are in bratislava.sk
> fix: change HOSTNAME to BRATISKA_HOSTNAME for redirects

- next/backend/graphql/index.ts
- next/backend/graphql/queries/Sections.graphql
- next/backend/meili/fetchers/blogPostsFetcherReactQuery.ts
- next/components/molecules/Sections.tsx
- next/components/molecules/sections/general/ArticlesListSection/BlogPostsByTags.tsx
- next/utils/useRoutePreservedState.ts
- strapi/config/plugins.meilisearch.config.ts
- strapi/schema.graphql
- strapi/src/api/blog-post/content-types/blog-post/schema.json
- strapi/src/api/page/content-types/page/schema.json
- strapi/src/components/sections/blog-posts-list.json
Note:
- add `addedAt` datetime field to BlogPosts, this filed will replace `date_added` and will be required in future (migration needed).
> #934: implement Blog Posts list by tags, prepared for future filtering

- next/components/ui/IconTitleDescItem/IconTitleDescItem.tsx
Changed IconTitleDescription to render as <Markdown> instead of <div>.
> Change IconTitleDescription from div to Markdown

- next/components/ui/ColumnedText/ColumnedText.tsx
New grid layout for different screen sizes:
lg allows at most 6 columns, stretches columns if fewer
md allows at most 4 columns, stretches columns if fewer
sm allows at most 2 columns, stretches columns if fewer
> Fix behaviour of ColumnedText allowing  more than 4 columns

- next/components/molecules/presentation/BlogPostCard.tsx
- next/styles/globals.css
I included two Safari fixes in this PR:
- https://github.com/bratislava/bratislava.sk/issues/1074
- https://github.com/bratislava/bratislava.sk/issues/1137
Added styles that remove any `list-style` and also style for removing the native Safari arrows.
Removed full height from CardBase, which was breaking styles on Safari on multiple occasions, while in Chrome it did not affect styles.
> Remove native arrows for accordion in Safari, Fix blog card in Safari

- next/components/molecules/presentation/BlogPostCard.tsx
- next/components/molecules/presentation/HomepageHorizontalCard.tsx
- next/components/molecules/presentation/MayorAndCouncilCard.tsx
- next/components/molecules/sections/general/CalculatorSection/MinimumCalculator.tsx
- next/components/molecules/sections/homepage/EventsHomepageSection.tsx
- next/components/molecules/sections/homepage/HomepageTabs/TabPanelLatestNews.tsx
- next/components/molecules/sections/homepage/HomepageTabs/TabPanelOfficialBoard.tsx
- next/components/molecules/sections/homepage/HomepageTabs/TabPanelRoadClosures.tsx
- next/components/ui/Banner/Banner.tsx
- next/components/ui/InBaCard/InBaCard.tsx
- next/components/ui/NumericalListSectionUI/NumericalListSectionUI.tsx
- next/components/ui/OfficialBoardCard/OfficialBoardCard.tsx
- next/pages/404.tsx
In future, consider to show link icon always by default, when button rendered as link.
> replace custom link icon by `hasLinkIcon` prop in buttons

- next/components/molecules/sections/general/AccordionSection.tsx
- next/components/ui/AccordionV2/AccordionV2.tsx
The `-large-gap` variants were added to meet legacy usage - we want to get rid off them now.
> remove legacy accordion bigger gap

- next/kubernetes/base/kustomization.yml
- next/kubernetes/base/old_aliases.ingress.yml
* As `old.bratislava.sk` and `old2.bratislava.sk` are turned off we want users to redirect to official main page
> chore: added old*.bratislava.sk aliases/redirects

- next/backend/graphql/index.ts
- next/components/molecules/SearchPageNew/useQueryBySearchOption.ts
- next/components/molecules/sections/general/RegulationsListSection/RegulationsListSection.tsx
- next/components/pages/RegulationPageContent.tsx
- next/messages/sk.json
---
✅ 
Regulation detail page - tag is displayed with `value` instead of display text:
---
✅
Typo - missing "k":
---
✅ 
Some Regulations do not have icon:
---
✅ 
It looks like its wrapped twice into `SectionWrapper`:
---
✅ 
The top padding should be part of page layout, not part of the search section. When used in "Regulations list" section, it adds unwanted space:
---
> Fix visuals

- next/backend/graphql/index.ts
- next/backend/graphql/queries/Sections.graphql
- next/components/molecules/Regulations/RegulationCard.tsx
- next/components/molecules/Regulations/Regulations.tsx
- next/components/molecules/Sections.tsx
- next/components/molecules/sections/general/RegulationsSection.tsx
- next/components/ui/FileList/FileList.tsx
- next/messages/en.json
- next/messages/sk.json
- strapi/schema.graphql
- strapi/src/api/blog-post/content-types/blog-post/schema.json
- strapi/src/api/page/content-types/page/schema.json
- strapi/src/components/sections/regulations.json
- ✅ create new component `Regulations` which behaves similarly to File list, but displays Regulations
- in all pages (production), replace current regulations (linked as files in File list) with the new Regulations component
- regulations are also referenced inside texts (sometimes without links, sometimes with links to files) - replace them with links to corresponding regulation pages
- afterwards we can remove duplicate regulation files from the Media Library
> 1158 3/replace vzn with regulations file list replacement

- strapi/config/middlewares.ts
https://docs.strapi.io/dev-docs/migration/v4/migration-guide-4.14.0-to-4.15.5
> move strapi logger middleware to first place to meet migration guides

- next/backend/graphql/index.ts
- next/backend/graphql/queries/Sections.graphql
- next/components/molecules/Sections.tsx
- next/components/molecules/sections/general/TestimonialsSection.tsx
- add FE components to Testimonials section
- testimonials render as `<blockquote>` with `<cite>` in `<footer>`
- TODO this should be validated if it is correct html syntax
- TODO render testimonials in unordered list
> add Testimonials FE components

- next/next.config.js
- next/pages/api/robots.ts
- remove all specific redirects of type `{ source; '/sprava/:slug', destination: '/blog/:slug' }` because they are matched by pattern matching 
- remove some duplicate redirects
- groups some related redirect just to have a better overview
- add robots.txt for production deployment
> #1261 Cleanup duplicate redirects

- next/components/cards/FileCardWrapper.tsx
- next/components/common/FileList/FileList.tsx
- Add border to the list that displays files in rows
- Replace div markup with an unordered list and list items
> #1299 Update FileList component according to DS

- next/kubernetes/envs/Staging/config.json
* Fix typo in suffix of Next memory limit from `mi` to `Mi`
> Fix typo in quantity suffix for staging resources

- next/services/graphql/index.ts
- next/services/graphql/queries/Sections.graphql
- strapi/src/components/blocks/file.json
- change wrongly set title from "long" to "short" (from text to string)
Notes:
- I checked if some of the titles are not longer that 256 characters - this would cause a problem in database when changing type of the field from text to string (string allows max 256 chars)
- I tested it deployed on dev with current production DB - it works nicely
> #1337 Change FileList item title from text to string

- strapi/README.md
- strapi/patches/@strapi+admin+4.10.8.patch
1. Run `yarn`, `yarn build`, `yarn dev`
2. Open Strapi
3. You should see all dynamic sections closed by default.
> #1374 Patch @strapi/admin to have all sections closed by default

- next/components/common/Iframe/Iframe.tsx
Strangely enough, we had to add `allow-forms` (not `allow-presentation`) into our iframe sandbox prop to make embedded PowerPoint presentations work.
> #1381 Add allow-forms into iframe sandbox

- next/services/graphql/index.ts
- strapi/schema.graphql
- strapi/src/components/blocks/file.json
- strapi/src/components/sections/file-list.json
Remove legacy fields from File list section in Strapi, run `yarn gen`.
These fields were not used anymore in FE.
Open some page that contains File list section, e.g. "Uzemne generely" and check if you see all section and files.
> #1303 Remove legacy FileList section fields

- next/src/components/formatting/Markdown/Markdown.module.scss
- next/src/components/formatting/Markdown/Markdown.tsx
- use styles for Markdown from OLO (it's mostly about mostly spacing)
- improve tables in markdown, based on OLO
Notes to tables:
- no scroll fade - TODO
Tables are on these pages:
`/mesto-bratislava/dane-a-poplatky`
`/zivotne-prostredie-a-vystavba/rozvoj-mesta/spoluucast-developerov-na-rozvoji-mesta`
`/doprava-a-mapy/doprava/dopravne-povolenia`    (v akordeone "Povolenie vjazdu..." a "Vyhradene parkovanie")
`/socialne-sluzby-a-byvanie/financna-podpora/financovanie-neverejnych-poskytovatelov-socialnych-sluzieb/socialne-sluzby-krizovej-intervencie`     (v akordeone)
Desktop
Mobile
(Note that there are non breaking spaces used in IBANs in Strapi)
> #1384 #1391 Improve markdown margins and tables

- next/src/components/common/Divider/HorizontalDivider.tsx
- next/src/components/common/FileList/FileList.tsx
- next/src/components/page-contents/InbaReleasePageContent.tsx
- next/src/components/page-contents/OfficialBoardDocumentPageContent.tsx
- next/src/components/page-contents/RegulationPageContent.tsx
- next/src/components/sections/SearchSection/SearchResultCard.tsx
- next/src/components/sections/SearchSection/SearchResults.tsx
- next/src/components/sections/homepage-sections/HomepageTabs/TabPanelOfficialBoard.tsx
- next/src/services/graphql/index.ts
- next/src/services/graphql/queries/Sections.graphql
Improve ui for file lists. I tried to implement a "ListBox" component, but ended in some problems, so I decides to only implement quickfix as small step for better filelists :D
All file lists should now have a box with border and dividers, and they should be in `<ul>`.
FileList section, e.g. here https://bratislava.sk/zivotne-prostredie-a-vystavba/rozvoj-mesta/uzemnoplanovacie-dokumenty/prerokovane-uzemnoplanovacie-podklady/uzemne-generely
Search page https://bratislava.sk/vyhladavanie
Regulation detail page https://bratislava.sk/vzn/11-2023
Official board on homepage in tab https://bratislava.sk/
Inba Release https://bratislava.sk/inba/archiv/in-ba-9-10-2023
Official Board documents
> #1332 Quickfix dividers and borders for file lists

- next/src/components/common/Bookmarks_Deprecated/Bookmark_Deprecated.tsx
- next/src/services/graphql/index.ts
- next/src/services/graphql/queries/BlogPosts.graphql
- next/src/utils/dev/strapiHelper.ts
- strapi/config/sync/admin-role.admin-clanky-lmg395y8.json
- strapi/config/sync/admin-role.admin-in-ba-lmg3a62g.json
- strapi/schema.graphql
- strapi/src/api/blog-post/content-types/blog-post/schema.json
- strapi/types/generated/contentTypes.d.ts
commit by commit
Note:
Using the strapiHelper, I checked if in all blogposts
- the title is shorter than 255 characters - to be able to make it short
- the title doesn't contain newlines (4 blogposts did, so I updated them) (some titles contain newline at the end, that is not a problem)
- the title is not empty/undefined/null - to be able to make it required
I check botch sk and en locales.
Note that `inert` is probably wrongly types. Using string worked before, using boolean doesn't work on prod (you can "tab" into the bookmark - this is not wanted)
Now on prod:
> #1486 Make BlogPost title required and short

- next/src/components/page-contents/BlogPostPageContent.tsx
- next/src/components/sections/ArticlesListSection/BlogPostsByCategory.tsx
- next/src/components/sections/ArticlesListSection/BlogPostsList.tsx
- next/src/components/sections/RelatedBlogPostsSection.tsx
- next/src/components/sections/SearchSection/useQueryBySearchOption.ts
- next/src/components/sections/homepage-sections/HomepageTabs/TabPanelLatestNews.tsx
- next/src/pages/api/feed.ts
- next/src/services/graphql/index.ts
- next/src/services/graphql/queries/BlogPosts.graphql
- next/src/services/meili/fetchers/blogPostsFetcher.ts
- next/src/utils/dev/strapiHelper.ts
- strapi/config/plugins.meilisearch.config.ts
- strapi/schema.graphql
- strapi/src/api/blog-post/content-types/blog-post/schema.json
- strapi/types/generated/contentTypes.d.ts
In BlogPosts:
- make `addedAt` required and use it everywhere (in meilisearch, sorting, cards...)
- remove `date_added`
Database is already updated on prod, where this was done:
- migrated `date_added` / `publishedAt` to addedAt
- updated `publishedAt` to reflect the manually entered date_added - this applies for blog posts that were oficially published before 2022 when new website was launged - therefore this needs to be done only once
- made sure that all blogposts have addedAt (so it can be made required)
> #1486 Use required addedAt in BlogPosts instead of date_added

- next/src/services/ms-graph/server/getGroupMembers.ts
/mesto-bratislava/sprava-mesta/magistrat/organizacna-struktura
> #1502 Move "sekretariat" and "asistent" higher in org. structure lists

- next/package-lock.json
- next/package.json
- next/src/components/cards/ArticleCard.tsx
- next/src/components/cards/transformArticleProps.ts
- next/src/components/cards/transformInbaArticleProps.ts
- next/src/components/page-contents/InbaArticlePageContent.tsx
- next/src/components/sections/ArticlesListSection/ArticlesAllSection.tsx
- next/src/components/sections/ArticlesListSection/ArticlesByCategory.tsx
- next/src/components/sections/ArticlesListSection/InbaArticlesList.tsx
- next/src/components/sections/RelatedArticlesSection.tsx
- next/src/components/sections/SearchSection/useQueryBySearchOption.ts
- next/src/components/sections/homepage-sections/HomepageTabs/TabPanelLatestNews.tsx
- next/src/services/graphql/index.ts
- next/src/services/graphql/queries/InbaArticles.graphql
- next/src/services/meili/fetchers/articlesFetcher.ts
- next/src/services/meili/fetchers/inbaArticlesFetcher.ts
- next/src/services/meili/types.ts
- next/src/utils/formatDate.ts
- create function that transforms strapi entity to card props (for Article and InbaArticle)
- use `formateDate` instead of legacy `getNumericLocalDate` + uninstall `@js-joda/core`
Testing: nothing should change on FE.
See these pages for usages:
- http://localhost:3000/mesto-bratislava
- http://localhost:3000/kontakty
- http://localhost:3000/vyhladavanie
- http://localhost:3000/inba
- http://localhost:3000/mesto-bratislava/transparentne-mesto/aktuality
> #1497 Simplify passing article props to ArticleCard

- next/src/components/common/Footer/DesktopFooter.tsx
- next/src/components/page-contents/ArticlePageContent.tsx
- next/src/components/page-contents/GeneralPageContent.tsx
- next/src/pages/[...slug].tsx
- next/src/services/graphql/index.ts
- next/src/services/graphql/queries/Pages.graphql
- strapi/config/sync/admin-role.strapi-super-admin.json
- strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##page.page.json
- strapi/schema.graphql
- strapi/src/api/page/content-types/page/schema.json
- strapi/types/generated/contentTypes.d.ts
- add `alias` field for Pages (Articles already had it, but not used)
- implement redirects with same approach as in OLO
- show info message when page/article has an alias (this was inspired by hel.fi website, also used on OLO)
- improve paddings on article page
- fix footer text size
This is a nice solution how to add an option for short urls, usually needed for sharing or campaigns, while keeping real urls inlined with sitemap nesting. 
Note that `alias` field is only visible for super admins for now, until properly tested.
Screenshots from localhost (no alias are set on production/staging):
> #1514 Create and use `alias` field for pages and articles

- tests/cypress/e2e/404Page.cy.ts
- tests/cypress/e2e/accountButton.cy.ts
- tests/cypress/e2e/englishTranslation.cy.ts
- tests/cypress/e2e/homepageSearch.cy.ts
- tests/cypress/e2e/officialBoard.cy.ts
- tests/cypress/e2e/organizationalStructure.cy.ts
- tests/cypress/e2e/searchPage.cy.ts
- tests/cypress/fixtures/URLsForSmokeTests.json
Setting cookiebot cookies to something prevents the banner to pop up, so it doesn't break the tests.
Update smokeTests urls.
> Fix cypress tests after CookieBot was introduced

- next/src/components/sections/AccordionSection.tsx
Testing:
Check accordions starting with "Pre koho sú zariadenia pre seniorov určené?"
http://localhost:3000/socialne-sluzby-a-byvanie/socialne-sluzby-a-zariadenia/zariadenia-a-sluzby-pre-seniorov
> #1539 Fix bug showing undefined link in accordions

- next/public/locales/en/translation.json
- next/public/locales/sk/translation.json
- next/src/components/common/ColumnedText/ColumnedText.tsx
- next/src/components/sections/ColumnedTextSection.tsx
- next/src/services/graphql/index.ts
- next/src/services/graphql/queries/Sections.graphql
- next/src/utils/dev/strapiHelper.ts
- strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.columned-text.json
- strapi/schema.graphql
- strapi/src/components/sections/columned-text.json
- strapi/types/generated/components.d.ts
- add `title` that is full width
- remove sparely used `contentAlignment` - I check it through the whole page - other than `left` or undefined was used only 2 times and it was not neceray because it was on partners logos.
> #1550 Add title to ColumnedText section and remove contentAlignment

- strapi/config/sync/admin-role.strapi-super-admin.json
- strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.documents.json
- strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##document-category.document-category.json
- strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##document.document.json
- strapi/schema.graphql
- strapi/src/api/document-category/content-types/document-category/schema.json
- strapi/src/api/document-category/controllers/document-category.ts
- strapi/src/api/document-category/routes/document-category.ts
- strapi/src/api/document-category/services/document-category.ts
- strapi/src/api/document/content-types/document/schema.json
- strapi/src/api/document/controllers/document.ts
- strapi/src/api/document/routes/document.ts
- strapi/src/api/document/services/document.ts
- strapi/src/api/page/content-types/page/schema.json
- strapi/src/components/sections/documents.json
- strapi/types/generated/components.d.ts
- strapi/types/generated/contentTypes.d.ts
- create new content types for Documents and Document Categories
- create new section
- export config-sync (add rights also to Admin, even though there is no FE yet, but Admins will see the new section nevertheless)
TODOs
- FE
> #1601 Create new Documents content type and section in Strapi

- strapi/src/customizations/document-service-middlewares.ts
- the 'sport' tag is added to a newly created article when created by starz admin
- **important addition** - during work on this PR I noticed an error when first saving a new article and only then publishing it - what fixed it, in document service middleware, was to search for the active user not by the createdBy property, but by the updatedBy property as this should in theory always retireve the active user
- log into strapi as a user with a starz role (the role needs to have 'starz' included in its name)
- create a new article, don't add any tag or adminGroup - only fill the required fields and publish the article
- you should now see that the article automatically recieved a tag "sport" and adminGroup "starz" (if you see weird text instead in the tag and adminGroup fields, ask me to …
> #1662 starz articles automatic sport tag for starz articles

- next/src/components/sections/ArticlesSection/ArticlesAll.tsx
- next/src/components/sections/ArticlesSection/ArticlesByCategory.tsx
- next/src/components/sections/InbaArticlesListSection.tsx
- next/src/components/sections/SearchSection/GlobalSearchSectionContent.tsx
- next/src/services/meili/fetchers/articlesFetcher.ts
- next/src/services/meili/fetchers/inbaArticlesFetcher.ts
- next/src/services/meili/fetchers/inbaReleasesFetcher.ts
- next/src/services/meili/fetchers/relatedArticlesFetcher.ts
- strapi/config/plugins.meilisearch.config.ts
- in articlesFetcher and inbaArticlesFetcher, we still filtered by id, but this clashed with some graphql queries which returned documentIds as values for these filters.
- in this PR, all fetchers now filter by documentIds
- on the [Aktuality](https://bratislava-next.staging.bratislava.sk/mesto-bratislava/transparentne-mesto/aktuality) page, selected other than "Všetky správy" - correct articles should be displayed
- Inba articles should be filterable by tag - try selecting some in [Inba archive](https://bratislava-next.staging.bratislava.sk/inba/archiv)
- check that related articles section at the bottom of pages display correctly - for example try the page [Pomoc a podpora](https://bratislava-next.staging.bratislava.sk/socialne-sluzby-a-byvanie/pomoc-a-podpora) which should display …
> 1681 fix articles fetching after strapi v5 upgrade

- next/src/components/layouts/SectionContainer.tsx
- next/src/components/layouts/Sidebars.tsx
- next/src/components/page-contents/GeneralPageContent.tsx
- next/src/services/graphql/index.ts
- next/src/services/graphql/queries/Pages.graphql
- next/src/services/graphql/queries/Sidebars.graphql
- strapi/config/sync/admin-role.admin-lg0mm2j6.json
- strapi/config/sync/admin-role.starz-md207wo9.json
- strapi/config/sync/admin-role.strapi-super-admin.json
- strapi/config/sync/core-store.plugin_content_manager_configuration_components##sidebars.empty-sidebar.json
- strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##page.page.json
- strapi/schema.graphql
- strapi/src/api/page/content-types/page/schema.json
- strapi/src/components/sidebars/empty-sidebar.json
- strapi/types/generated/components.d.ts
- strapi/types/generated/contentTypes.d.ts
Sidebar shrinks, but stays in the right column until less than 288px wide.
Right column is less than 288px wide, so sidebar displays on top of the left column.
> #1663 starz page layout with sidebar

- next/src/components/common/PageHeader/PageHeader.tsx
- next/src/components/layouts/PageHeaderSections.tsx
- next/src/components/page-contents/GeneralPageContent.tsx
- next/src/components/sections/headers/SubpageListPageHeaderSection_Deprecated.tsx
- strapi/src/api/page/content-types/page/schema.json
- strapi/types/generated/contentTypes.d.ts
PageHeaderSections was restructured to allow for more page header types needed in STARZ.
Some caveats:
- some fields used in headers (headerLinks, pageBackgroundImage) can be filled directly from the page entry, however they are used only in some headers - in future, they may be moved to a specific header so it is clear for the content admin that these fields are relevant only for some headers
No visible changes - everything should stay as before
> #1739 Refactor page headers to allow more header types

- tests/cypress/e2e/404Page.cy.ts
We don't have to check the title. Image (and link is enought).
Note that cypress tests sometimes don't pass due to cookie banner.
> #1644 Fix 404 test after changes

- next/README.md
- next/package-lock.json
- next/package.json
- next/scripts/dev/getAllUsedFilesInMediaLibrary.ts
- next/scripts/dev/migrateFilesToDocuments.ts
- next/scripts/dev/migrateSubnavigation.ts
- next/src/services/graphql/index.ts
- next/src/services/graphql/queries/Files.graphql
- next/src/services/graphql/queries/Pages.graphql
- next/tsconfig.json
We want to be able to run some .ts scripts locally (to lis pages, to list some specific sections use-cases etc.).
We can achieve it by using `ts-node` (as it is used in konto project).
Additionally to konto, we install also
- `dotenv` - to be able to read .env variables from a file - to get strapi url
- strapi url can pottentially be hardcoded in the script 🤷 and we will not need `dotenv`
- `tsconfig-paths/register` - because we use path aliases in tsconfig (`@/*`)
I committed also some scripts, that I started to write, but they are only temporary or they will get stale with more strapi changes. These scripts are mostly for migration purposes around Files and Documents and Subnavigation.
I don't know yet what "policy" we will have about committing such kind of code, but it's in dev …
> Setup running local scripts with ts-node

- next/src/components/layouts/SectionHeader.tsx
- next/src/components/sections/RelatedArticlesSection.tsx
Implemented as a prop to SectionHeader - pondered a minute about naming, chose `excludeFromTableOfContents` which seems to me the most legible when actually using this prop:
> #1772 Enable hiding SectionHeader heading from ToC, hide in RelatedArticlesSection

- next/src/components/sections/ArticlesSection/ArticlesFiltered.tsx
- next/src/components/sections/ArticlesSection/ArticlesSection.tsx
- next/src/services/fetchers/homepageContextFetcher.ts
- next/src/services/graphql/index.ts
- next/src/services/graphql/queries/AdminGroups.graphql
- next/src/services/graphql/queries/Sections.graphql
- next/src/services/meili/fetchers/articlesFetcher.ts
- strapi/config/plugins.meilisearch.config.ts
- strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.articles.json
- strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.documents.json
- strapi/config/sync/user-role.public.json
- strapi/schema.graphql
- strapi/src/components/sections/articles.json
- strapi/src/components/sections/documents.json
- strapi/types/generated/components.d.ts
- ArticlesSection
- HomepageTags
- Documents (low priority)
- best reviewed commit by commit
- In ArticlesSection, showMoreLink can be added when filtering by tags or adminGroups. If we want to point this link to the main Aktuality page, then it needs to be filled in by super admin, because starz admin would not see that relation (due to admingroups role based access). An alternative would be to hardcode the link to Aktuality page.
- deviations from Figma
- ArticlesSection background set to white
- Carousel controls variant set to bottom
> #1660 Refactor main content-type sections to handle starz content

- next/public/locales/en/translation.json
- next/public/locales/sk/translation.json
- next/src/components/cards/ContactCtaCard.tsx
Use short urls in form of `https://maps.app.goo.gl/...` from "Share modal":
This is the desired width of map. All individual contacts have limited width to this size.
> #1788 Fix iframe map size and title translation

- next/public/locales/en/translation.json
- next/public/locales/sk/translation.json
- next/scripts/dev/listPages.ts
- next/src/components/cards/DocumentRowCard.tsx
- next/src/components/cards/LinkRowCard.tsx
- next/src/components/common/Button/Button.tsx
- next/src/components/common/Links/Links.tsx
The aim was to quickly improve Links section design, without huge effort. Design is taken from ux workshop figma, it's not in DS yet. Implementing only simple internal/external link, not "document link".
- implement LinkRowCard 
- tested with long urls also on mobile - I decided to use `break-all` class on metadata, to prevent overflow, even tho it breaks url anywhere in the middle of words, but it doesn't matter with urls I think
Some urls to test on:
/mesto-bratislava/sprava-mesta/legislativa-mesta/zakony
/mesto-bratislava/sprava-mesta/volene-organy/komunalne-volby
/socialne-sluzby-a-byvanie/socialne-sluzby-a-zariadenia/zariadenia-a-sluzby-pre-seniorov
> #1841 Redesign Links section
